project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "*.md"
    - "!LICENSE.md"

website:
  title: "EDS 214: Analytical Workflows and Scientific Reproducibility"
  favicon: images/bren-hex.png
  navbar:
    right:
      - href: index.qmd
        text: home
      - text: syllabus
        href: https://docs.google.com/document/d/1lw79wgi5v-BZkKc7BmGwXzLmDkmj87-lPcopE3eDdBQ/edit?usp=sharing
        target: _blank
      - text: course materials
        menu:
          - text: day 1 (8/25)
            href: course-materials/day1.qmd
          - text: day 2 (8/26)
            href: course-materials/day2.qmd
          - text: day 3 (8/27)
            href: course-materials/day3.qmd
          - text: day 4 (8/28)
            href: course-materials/day4.qmd
          - text: day 5 (8/29)
            href: course-materials/day5.qmd
      - text: final project
        href: course-materials/final-project/final-project.qmd
      - text: resources
        menu: 
          - text: recommended readings & resources
            href: resources.qmd
          - text: MEDS installation guide
            href: https://ucsb-meds.github.io/MEDS-installation-guide/
            target: _blank
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/UCSB-MEDS/EDS-website-template
          - text: Report a Bug
            url: https://github.com/UCSB-MEDS/EDS-website-template/issues
  page-footer:
    background: dark
    right: This website is built with [{{< fa brands github title="the github octocat logo" >}}](https://github.com/UCSB-MEDS/EDS-website-template) and [Quarto](https://quarto.org/)
    left: This work is licensed under CC BY-NC 4.0. 

extensions:
  - bren-meds-courses

format:
  html:
    theme: meds-website-styles.scss
    page-layout: full
    toc: true
    title-block-banner: true

