---
title: "Git and GitHub for Workflows"
subtitle: "Day 3"
description: "Wednesday August 27^th^, 2025"
bibliography: references.bib
---

## Class materials

| {{< session >}} | {{< lecture >}} | {{< interactive >}} | {{< reflection >}} |
|------------------|------------------|------------------|------------------|
| Morning | [Version control with git](lecture-slides/lecture-day3am-slides.qmd){target="_blank"} | [Git branching](interactive/interactive-day3am.qmd) | Morning reflection |
| Afternoon | [Collaboration with GitHub](lecture-slides/lecture-day3pm-slides.qmd){target="_blank"} | [Refactor a function](interactive/interactive-day3pm.qmd) | Afternoon reflection |

: {.hover .bordered}

## Further reading

-   @bryan2018 explains why data scientists should embrace the project management benefits of git and GitHub

> In my opinion, *for new users*, the advantages of Git only outweigh the disadvantages when you consider the overhead of working with other people, including your future self. And who among us does not need to do that? In a Git-based workflow, you document and, optionally, expose your work as you go. Communication and collaboration are the killer apps of version control. Git's model of file management can feel uncomfortably rigid, but it enables the distribution of files across different people, computers, and time.

-   @braga2023 present 12 reasons scientists should use GitHub for collaboration, communication, and project management.
